In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("Input.xlsx")
df.head()

   Order Date    Product     Category  Price  Quantity
0  2023-01-01  Product A  Electronics    500         2
1  2023-01-03  Product B     Clothing     40         3
2  2023-01-05  Product C  Electronics   1200         1
3  2023-02-10  Product A  Electronics    500         1
4  2023-02-15  Product B     Clothing     40         2

In [3]:
df["Total"] = df["Price"] * df["Quantity"]
df.head()

   Order Date    Product     Category  Price  Quantity  Total
0  2023-01-01  Product A  Electronics    500         2   1000
1  2023-01-03  Product B     Clothing     40         3    120
2  2023-01-05  Product C  Electronics   1200         1   1200
3  2023-02-10  Product A  Electronics    500         1    500
4  2023-02-15  Product B     Clothing     40         2     80

In [4]:
df.head()

   Order Date    Product     Category  Price  Quantity  Total
0  2023-01-01  Product A  Electronics    500         2   1000
1  2023-01-03  Product B     Clothing     40         3    120
2  2023-01-05  Product C  Electronics   1200         1   1200
3  2023-02-10  Product A  Electronics    500         1    500
4  2023-02-15  Product B     Clothing     40         2     80

In [5]:
df.to_excel("output.xlsx", index=False)